config:
  dependencies:
    - name: WebServer
      instance: '../Contexts/Server/infrastructure/ExpressAdapter'
      args:
        - 'PORT'
    - name: Health
      instance: '../Contexts/Health/application/health'
    - name: NotFound
      instance: '../Contexts/NotFound/application/notFound'
