config:
  dependencies:
    - name: WebServer
      instance: '../Contexts/Server/infrastructure/ExpressAdapter'
      args:
        - 'PORT'
    - name: Health
      instance: '../Contexts/Health/application/health'
    - name: NotFound
      instance: '../Contexts/NotFound/application/notFound'
    - name: OrderRepository
      instance: '../Contexts/Order/infrastructure/Mock/MockOrderRepository'
    - name: Order
      instance: '../Contexts/Order/application/order'
    - name: Database
      instance: '../Contexts/Database/infrastructure/MockDatabase'
