version: "3.9"

services:
  mongodb:
    env_file:
      - mongo.env
    build:
      context: .
      dockerfile: mongo.Dockerfile
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27017"
    networks:
      mongonetwork:
  api:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: hexa-shopping-cart-orders-api
    env_file:
      - .env.dev
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"
    depends_on: 
      - mongodb
    links:
      - mongodb
    networks:
      mongonetwork:
networks:
  mongonetwork:
    driver: bridge