version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: develop.Dockerfile
    container_name: hexa-shopping-cart-orders-api
    env_file:
      - .env.test
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3000"