version: "3.9"

services:
  mongodb:
    env_file:
      - mongo.env
    build:
      context: .
      dockerfile: mongo.Dockerfile
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27018:27017"
    networks:
      mongonetwork:
networks:
  mongonetwork:
    driver: bridge